name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v2
      with:
        name: Atomaker-Linux
        path: Atomaker
